In [1]:
import numpy as np
five_store = np.random.randint(100,10000,size=(5,30)) 
five_store_cumsum = five_store.cumsum(axis=1)
five_store_cumsum

array([[  6002,  14705,  23768,  27018,  35868,  42684,  47542,  50265,
         53169,  61417,  65301,  69067,  77340,  80747,  86141,  94795,
        104643, 111288, 118168, 118386, 127743, 135248, 142792, 152289,
        154018, 160785, 162269, 165754, 168480, 174332],
       [  3548,  10011,  11097,  12811,  15563,  22804,  30790,  31134,
         38868,  42488,  47539,  52118,  55855,  58716,  59532,  67613,
         73567,  75860,  85398,  85801,  94470,  94894, 104342, 109735,
        119215, 126147, 126346, 133227, 142151, 142517],
       [  3791,  10627,  15465,  15679,  20126,  20460,  21468,  22915,
         24165,  26166,  31891,  38300,  46528,  51461,  58811,  63782,
         70363,  72137,  80469,  85012,  89015,  89928,  94847,  95908,
        100240, 102345, 105941, 110028, 117627, 118254],
       [  5638,   7724,  14268,  22352,  31493,  41422,  46887,  48213,
         53554,  61679,  64214,  72413,  73908,  74776,  82532,  91432,
        100605, 105307, 106952, 107207, 114854, 114955, 121595, 131388,
        135773, 142567, 145595, 151682, 156272, 165681],
       [  4948,   6978,  16885,  18385,  27449,  28912,  32317,  36444,
         44590,  53970,  56379,  66290,  75992,  76922,  81071,  85179,
         86025,  86882,  88024,  90499,  97430, 107254, 110048, 119992,
        124647, 133380, 133931, 143230, 152230, 160846]])

In [8]:
import pandas as pd

five_store = pd.DataFrame(five_store_cumsum,
             columns=[f"第{day}天"for day in range(1,31)],
             index=["台北分店","新竹分店","台中分店","台南分店","高雄分店"])
five_store.T

        台北分店    新竹分店    台中分店    台南分店    高雄分店
第1天     6002    3548    3791    5638    4948
第2天    14705   10011   10627    7724    6978
第3天    23768   11097   15465   14268   16885
第4天    27018   12811   15679   22352   18385
第5天    35868   15563   20126   31493   27449
第6天    42684   22804   20460   41422   28912
第7天    47542   30790   21468   46887   32317
第8天    50265   31134   22915   48213   36444
第9天    53169   38868   24165   53554   44590
第10天   61417   42488   26166   61679   53970
第11天   65301   47539   31891   64214   56379
第12天   69067   52118   38300   72413   66290
第13天   77340   55855   46528   73908   75992
第14天   80747   58716   51461   74776   76922
第15天   86141   59532   58811   82532   81071
第16天   94795   67613   63782   91432   85179
第17天  104643   73567   70363  100605   86025
第18天  111288   75860   72137  105307   86882
第19天  118168   85398   80469  106952   88024
第20天  118386   85801   85012  107207   90499
第21天  127743   94470   89015  114854   97430
第22天  135248   94894   89928  114955  107254
第23天  142792  104342   94847  121595  110048
第24天  152289  109735   95908  131388  119992
第25天  154018  119215  100240  135773  124647
第26天  160785  126147  102345  142567  133380
第27天  162269  126346  105941  145595  133931
第28天  165754  133227  110028  151682  143230
第29天  168480  142151  117627  156272  152230
第30天  174332  142517  118254  165681  160846