In [15]:
import numpy as np
import pandas as pd
scores = np.random.randint(50,101,size=(50,5)) #50分到~100分 size=50,5 50個列 5個欄
scores_df = pd.DataFrame(scores,index=range(1,51),columns=['國文', '英文', '數學', '地理', '歷史'])
scores_df.index.name = "學號"
scores_df.columns.name = "科目"
scores_df

科目   國文  英文   數學   地理   歷史
學號
1    80  58   70   92   57
2    89  79  100   70   98
3    80  67   83   58   50
4    63  88   71   60   92
5    72  67   56   99   74
6    51  79   65   86   90
7    97  52   68   86   57
8    65  87   72   60   52
9    94  99   67   92   76
10   59  68   62   91   84
11   92  88   86   95   62
12   63  55   62   50   93
13   85  77   55   87   96
14   54  67   99   89   62
15   71  58   79   84   55
16   81  77   73   60   52
17   76  86   73   70   82
18   72  77   79   63   51
19   93  77   53   50   96
20   54  60   57   76   76
21  100  87   86   81   75
22   66  83   79   61   53
23   56  68   87   61   68
24   89  61   97   88   55
25   61  91   86   58   93
26   74  61   58   84   77
27   63  83   69   76   89
28   52  63   73   75   86
29   98  94   88   94   70
30   54  97   50   70   69
31   67  59   85   95   88
32   90  96  100   51   71
33   80  59   69  100   64
34   52  71   62   95  100
35   73  82   53   81   71
36   62  94   90   64   94
37   94  50   60   58   91
38   64  88   77   74   66
39   91  83   86   64   92
40   65  69  100   64   76
41   69  59   98   72   69
42   88  83   55   69   53
43   94  63   68   60   71
44   63  72   68   86   78
45   64  94   90   80   92
46   51  90   50   78   82
47   69  66   81   71   77
48   77  52   81   54   83
49   57  78   97   73   50
50   61  88   89   84   55

In [16]:
scores_df1 = scores_df.copy()

In [ ]:
def cal1(s):        #s是Series  直行的是Series ex: 國文1~50
    return s.sum()
scores_df.apply(cal1,axis=1)    #axis=1 是橫的 ex: 1號 國文75 英文81 數學89	地理92 歷史85

In [ ]:
s1 = scores_df.iloc[1]    #iloc[0] 抓第一筆
int(s1[s1<70].count())         #count() 統計數量

In [17]:
def cal2(s):
    nums = int(s[s<60].count())        
    return nums
scores_df1['不及格的科目'] = scores_df.apply(cal2,axis=1) 
scores_df1

科目   國文  英文   數學   地理   歷史  不及格的科目
學號
1    80  58   70   92   57       2
2    89  79  100   70   98       0
3    80  67   83   58   50       2
4    63  88   71   60   92       0
5    72  67   56   99   74       1
6    51  79   65   86   90       1
7    97  52   68   86   57       2
8    65  87   72   60   52       1
9    94  99   67   92   76       0
10   59  68   62   91   84       1
11   92  88   86   95   62       0
12   63  55   62   50   93       2
13   85  77   55   87   96       1
14   54  67   99   89   62       1
15   71  58   79   84   55       2
16   81  77   73   60   52       1
17   76  86   73   70   82       0
18   72  77   79   63   51       1
19   93  77   53   50   96       2
20   54  60   57   76   76       2
21  100  87   86   81   75       0
22   66  83   79   61   53       1
23   56  68   87   61   68       1
24   89  61   97   88   55       1
25   61  91   86   58   93       1
26   74  61   58   84   77       1
27   63  83   69   76   89       0
28   52  63   73   75   86       1
29   98  94   88   94   70       0
30   54  97   50   70   69       2
31   67  59   85   95   88       1
32   90  96  100   51   71       1
33   80  59   69  100   64       1
34   52  71   62   95  100       1
35   73  82   53   81   71       1
36   62  94   90   64   94       0
37   94  50   60   58   91       2
38   64  88   77   74   66       0
39   91  83   86   64   92       0
40   65  69  100   64   76       0
41   69  59   98   72   69       1
42   88  83   55   69   53       2
43   94  63   68   60   71       0
44   63  72   68   86   78       0
45   64  94   90   80   92       0
46   51  90   50   78   82       2
47   69  66   81   71   77       0
48   77  52   81   54   83       2
49   57  78   97   73   50       2
50   61  88   89   84   55       1

In [32]:
#5個Series傳出成DataFrame
def cal3(s):
    return pd.Series([s.min(),s.max(),s.std()],index=['最低分','最高分','標準差'])
scores_df3 = scores_df.apply(cal3)          #apply(function)

In [33]:
display(scores_df)
scores_df3

科目   國文  英文   數學   地理   歷史
學號
1    80  58   70   92   57
2    89  79  100   70   98
3    80  67   83   58   50
4    63  88   71   60   92
5    72  67   56   99   74
6    51  79   65   86   90
7    97  52   68   86   57
8    65  87   72   60   52
9    94  99   67   92   76
10   59  68   62   91   84
11   92  88   86   95   62
12   63  55   62   50   93
13   85  77   55   87   96
14   54  67   99   89   62
15   71  58   79   84   55
16   81  77   73   60   52
17   76  86   73   70   82
18   72  77   79   63   51
19   93  77   53   50   96
20   54  60   57   76   76
21  100  87   86   81   75
22   66  83   79   61   53
23   56  68   87   61   68
24   89  61   97   88   55
25   61  91   86   58   93
26   74  61   58   84   77
27   63  83   69   76   89
28   52  63   73   75   86
29   98  94   88   94   70
30   54  97   50   70   69
31   67  59   85   95   88
32   90  96  100   51   71
33   80  59   69  100   64
34   52  71   62   95  100
35   73  82   53   81   71
36   62  94   90   64   94
37   94  50   60   58   91
38   64  88   77   74   66
39   91  83   86   64   92
40   65  69  100   64   76
41   69  59   98   72   69
42   88  83   55   69   53
43   94  63   68   60   71
44   63  72   68   86   78
45   64  94   90   80   92
46   51  90   50   78   82
47   69  66   81   71   77
48   77  52   81   54   83
49   57  78   97   73   50
50   61  88   89   84   55

科目           國文         英文          數學          地理          歷史
最低分   51.000000  50.000000   50.000000   50.000000   50.000000
最高分  100.000000  99.000000  100.000000  100.000000  100.000000
標準差   14.733344  13.760339   14.877129   14.207342   15.352737

In [34]:
pd.concat([scores_df,scores_df3])   #pd.concat 連接2個function

科目           國文         英文          數學          地理          歷史
1     80.000000  58.000000   70.000000   92.000000   57.000000
2     89.000000  79.000000  100.000000   70.000000   98.000000
3     80.000000  67.000000   83.000000   58.000000   50.000000
4     63.000000  88.000000   71.000000   60.000000   92.000000
5     72.000000  67.000000   56.000000   99.000000   74.000000
6     51.000000  79.000000   65.000000   86.000000   90.000000
7     97.000000  52.000000   68.000000   86.000000   57.000000
8     65.000000  87.000000   72.000000   60.000000   52.000000
9     94.000000  99.000000   67.000000   92.000000   76.000000
10    59.000000  68.000000   62.000000   91.000000   84.000000
11    92.000000  88.000000   86.000000   95.000000   62.000000
12    63.000000  55.000000   62.000000   50.000000   93.000000
13    85.000000  77.000000   55.000000   87.000000   96.000000
14    54.000000  67.000000   99.000000   89.000000   62.000000
15    71.000000  58.000000   79.000000   84.000000   55.000000
16    81.000000  77.000000   73.000000   60.000000   52.000000
17    76.000000  86.000000   73.000000   70.000000   82.000000
18    72.000000  77.000000   79.000000   63.000000   51.000000
19    93.000000  77.000000   53.000000   50.000000   96.000000
20    54.000000  60.000000   57.000000   76.000000   76.000000
21   100.000000  87.000000   86.000000   81.000000   75.000000
22    66.000000  83.000000   79.000000   61.000000   53.000000
23    56.000000  68.000000   87.000000   61.000000   68.000000
24    89.000000  61.000000   97.000000   88.000000   55.000000
25    61.000000  91.000000   86.000000   58.000000   93.000000
26    74.000000  61.000000   58.000000   84.000000   77.000000
27    63.000000  83.000000   69.000000   76.000000   89.000000
28    52.000000  63.000000   73.000000   75.000000   86.000000
29    98.000000  94.000000   88.000000   94.000000   70.000000
30    54.000000  97.000000   50.000000   70.000000   69.000000
31    67.000000  59.000000   85.000000   95.000000   88.000000
32    90.000000  96.000000  100.000000   51.000000   71.000000
33    80.000000  59.000000   69.000000  100.000000   64.000000
34    52.000000  71.000000   62.000000   95.000000  100.000000
35    73.000000  82.000000   53.000000   81.000000   71.000000
36    62.000000  94.000000   90.000000   64.000000   94.000000
37    94.000000  50.000000   60.000000   58.000000   91.000000
38    64.000000  88.000000   77.000000   74.000000   66.000000
39    91.000000  83.000000   86.000000   64.000000   92.000000
40    65.000000  69.000000  100.000000   64.000000   76.000000
41    69.000000  59.000000   98.000000   72.000000   69.000000
42    88.000000  83.000000   55.000000   69.000000   53.000000
43    94.000000  63.000000   68.000000   60.000000   71.000000
44    63.000000  72.000000   68.000000   86.000000   78.000000
45    64.000000  94.000000   90.000000   80.000000   92.000000
46    51.000000  90.000000   50.000000   78.000000   82.000000
47    69.000000  66.000000   81.000000   71.000000   77.000000
48    77.000000  52.000000   81.000000   54.000000   83.000000
49    57.000000  78.000000   97.000000   73.000000   50.000000
50    61.000000  88.000000   89.000000   84.000000   55.000000
最低分   51.000000  50.000000   50.000000   50.000000   50.000000
最高分  100.000000  99.000000  100.000000  100.000000  100.000000
標準差   14.733344  13.760339   14.877129   14.207342   15.352737